In [154]:
import pandas as pd
import numpy as np 
import math

In [155]:
df = pd.read_csv("dataclassification.csv")
df

User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]

In [156]:
df.isnull().sum()

User ID            0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [157]:
X = df.iloc[:,:3]
y = df.Purchased
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)

In [158]:
from sklearn.tree import DecisionTreeClassifier
classification = DecisionTreeClassifier()
classification.fit(X_train, y_train)
predictions = classification.predict(X_test)

In [159]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,predictions)

array([[56,  2],
       [ 5, 17]])

In [160]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)*100

91.25

In [161]:
classification.predict([[182284,21,42000]])

array([0])

In [162]:
classification.predict([[182284,19,10000]])

array([0])

In [163]:
classification.predict([[182285,36,93122]])


array([1])

In [164]:
classification.predict([[182286,32,23123]])


array([0])

In [165]:
classification.predict([[182287,48,67000]])

array([0])

In [166]:
classification.predict([[182288,62,32000]])

array([1])