In [15]:
import pandas as pd
import numpy as np


In [16]:
df = pd.read_csv("dataclassification.csv")
df

User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]

In [17]:
X = df.iloc[:,:3]
y = df.Purchased

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [19]:
from sklearn.tree import DecisionTreeClassifier
classification = DecisionTreeClassifier()
classification.fit(X_train, y_train)
predictions = classification.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[56,  2],
       [ 4, 18]])

In [21]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, predictions)*100
print(accuracy, '%')

92.5 %


In [22]:
classification.predict([[182284,21,42000]])

array([0])

In [23]:
classification.predict([[182284,19,10000]])

array([0])

In [24]:
classification.predict([[182285,36,93122]])

array([1])

In [25]:
classification.predict([[182286,32,23123]])

array([0])

In [26]:
classification.predict([[182287,48,67000]])

array([0])

In [27]:
classification.predict([[182288,62,32000]])

array([1])